### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by frank984** [semyonbok/multiclass-proba-contour#1] opened 2022-05-05 09:20 UTC
By running your code I encourred in this type of error:
![image](https://user-images.githubusercontent.com/6491927/166894656-d1e1f942-7aba-4732-ac2b-cfcf1ea98eec.png)
The Python version is the 3.8.8

**Comment by semyonbok** [comment] 2022-05-05 10:06
Hi @frank984, thank you for reaching out. The problem is in type hinting (I generally did not do a good job at that). It appears that the convention I used is applicable for Python 3.9+. For 3.8, the container type, `tuple` in our case, ought to be capitalised. The link below will give you more details (**Built-in types** section).

https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html

**Comment by frank984** [comment] 2022-05-05 11:37
Thank you for your fast answer. I have capitalized `Tuple` but it doesn't work:
![image](https://user-images.githubusercontent.com/6491927/166915524-62afd250-e2e6-4d4b-983f-80af4793534c.png)

**Comment by semyonbok** [comment] 2022-05-05 12:22
@frank984, a tiny detail that I should have mentioned is that `Tuple`  should be imported from [typing](https://docs.python.org/3/library/typing.html#) module, as explained in the above-attached link. 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/94805866/166918432-6a061c48-0a94-42a6-a620-59e0edbe0383.png">

Clearly, I will need to work on a more robust type hinting. As a quick fix, may I suggest removing code `: tuple[int, int]` from lines 62, 106, and 174.

Let me know if anything else breaks :)

**Comment by semyonbok** [comment] 2022-05-07 21:41
@frank984, I've committed some fixes, including framing hinted types in quotes. `TypeError` was not raised in a Python 3.8 environment by running a file with a similar hinting format. Thus, I am closing the issue. :)

**Closed as completed by semyonbok** 2022-05-07 21:41 UTC
